public/index.html, src/style/global.jsx
=> #9 - Chore: 폰트 스타일 추가

src/App.jsx, src/components/navigator/NavigatorMenu.jsx, src/components/navigator/NavigatorMenu.style.jsx
1. 모바일 화면 사이즈 일 때 나타나도록 조건 추가
2. App.jsx에서 분리하여 각 사용되는 페이지에서만 사용되도록 수정
- 작업한 페이지 모바일 버전에 네비게이션 바가 있다면 페이지에 `<NavigatorMenu />` 추가
=> #42 - Fix : 네비게이션 바 조건 추가

src/components/Common/header/FeedHeader.jsx, src/components/Common/header/FeedHeader.style.jsx, src/components/Common/header/Header.jsx, src/components/Common/post/PostUploadImg.jsx, src/components/Common/post/PostUploadImg.style.jsx, src/components/postUpload/PostUpHeader.jsx, src/components/search/SearchHeader.jsx
- 어제 수정한 header 부분 경로가 잘못된 부분이 있어 수정했습니다.
- Link 태그의 속성이 href로 되어있어 라우터 오류가 있었습니다. 해당 부분 수정했습니다.
=> #60 - Fix: header 경로 및 오타 수정

src/components/common/post/PostUploadImg.jsx, src/components/common/post/PostViewImg.jsx, src/components/common/post/PostViewImg.style.jsx, src/components/postUpload/PostForm.jsx, src/components/productAdd/ProductForm.jsx, src/components/productAdd/ProductForm.style.jsx
url: /product 에서 확인 가능
포스팅 상세일 때랑 등록일 때에 따라 마크업 다르게 나오도록 수정했습니다.
파일 여러개할 지 1개올릴지 수정했습니다.
- 서버에 상품 등록하기 완료
- style : 업로드 되는 이미지에 맞게 높이가 조절되도록 수정했습니다.
=> #72 - Feat: 상품등록 기능

src/components/login/LoginForm.jsx
83-84번째 줄 추가하였습니다!!
북더기 이름으로 회원가입 해놓았습니다!
아이디 : book@duk.com
비밀번호 : bookduk
이미지 : 채팅 강아지 사진
사용자이름 : 북더기
계정 ID : bookduk
소개 : 안뇽
accountname: "bookduk"
email: "book@duk.com"
image: "https://mandarin.api.weniv.co.kr/1658426463250.png"
intro: "안뇽"
refreshToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg0MjY2MjAsImV4cCI6MTY1OTYzNjIyMH0.e0bpSkbvdD4OZluh88Zs44GtoCYK8zGRLgibjAQfxxg"
token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDk5NGNmMTdhZTY2NjU4MTg0Y2QyMCIsImV4cCI6MTY2MzYxMDYyMCwiaWF0IjoxNjU4NDI2NjIwfQ.MGJaNjVD65OOThNnwj_EOd-mlWnj-EsYkIZlBoPOF2g"
username: "북더기"
_id: "62d994cf17ae66658184cd20"
=> #75 - Feat : 로그인 정보 로컬스토리지 저장

src/App.jsx, src/components/join/JoinForm.jsx, src/components/join/JoinProfile.style.jsx, src/components/join/JoinProfileForm.jsx, src/pages/JoinPage.jsx, src/pages/JoinProfilePage.jsx
- components/join 폴더 생성
- joinForm.jsx : 회원가입 첫번째 페이지 
- 아이디 비밀번호 설정 후 다음 페이지로 아이디, 비밀번호 넘겨줌
- api 통신 전에 이메일, 비밀번호 유효성 검사 후  user/emailvaild와 api 통신할 때 이메일 유효성 검사 진행
- 아이디, 비밀번호 둘 다 input창에 입력되어야 버튼 활성화
- joinProfileForm.jsx : 회원가입 두 번째 페이지
- 이미지 파일 인코딩 후 image/uploadfile api통신하여 파일 이름 숫자로 변경 후 보내기
- 이미지 업로드 버튼과 input -> useRef 사용하여 연결함(inputClick)
- 사용자 이름, 계정 ID 유효성 검사 진행 후 api 통신하여 accountnamevalid로 계정 id 유효성 검사 진행 후 user로 회원정보 내용 post전송
- 사용자 이름, 계정 ID 만 필수이므로 둘 다 input창에 입력되어야 버튼 활성화
+ 이미지 유효성 검사는 추후에 추가하겠습니다ㅠㅠ 잘 안되네용,,흙
=> #23 - Feat : 회원가입 기능

src/App.jsx
=> #80 - Refactor : 라우트 변경

src/App.jsx, src/components/common/Button.style.jsx, src/components/common/post/PostUploadImg.jsx, src/components/profile/edit/EditAccount.jsx, src/components/profile/edit/EditIntro.jsx, src/components/profile/edit/EditUsername.jsx, src/components/profile/edit/ProfileEdit.jsx, src/pages/ProfileEditPage.jsx
프로필 수정 기능 완료
- 마이페이지에서 수정 버튼 누를 시 등장
- 기존 프로필 내용을 인풋 값으로 셋팅
- 수정 완료 후 성공적으로 끝나면 로컬 내용 변경 및 마이 프로필 페이지로 이동
=> #97 - Feat: 프로필 수정

src/components/profile/ProfileInfo.jsx
내 프로필 팔로잉/ 팔로워 경로 
_id -> accountname 으로 변경하였습니다
=> #108 - BREAKING CHANGE: 내 프로필 팔로잉/팔로워 경로 수정

src/components/common/Input.style.jsx, src/components/common/user/User.jsx, src/components/postUpload/PostForm.jsx, src/components/postUpload/PostUpContainer.jsx, src/components/postView/PostViewContainer.jsx, src/components/postView/comment/CommentContainer.jsx, src/components/postView/comment/CommentForm.jsx, src/components/productAdd/ProductForm.jsx, src/components/productAdd/ProductForm.style.jsx, src/components/productAdd/ProductLink.jsx, src/components/productAdd/ProductName.jsx, src/components/productAdd/ProductPrice.jsx, src/components/search/SearchHeader.jsx, src/components/search/SearchHeader.style.jsx, src/pages/PostUploadPage.jsx, src/style/theme.js
1. 게시물 등록 / 상품 등록 / 게시물 상세 / 댓글 / 검색 페이지
- 404에러 시 에러 페이지로 넘어가게 수정
- 각 페이지에 완료가 안되도 submit 이벤트가 일어나는 현상 수정
2.  상품 등록 
입력값에 따른 유효성 검사 수정
3. 유저 이미지가 서버 주소가 아닐 경우 기본이미지로 보이도록 수정
=> #99 - Fix: 에러처리, 유효성 검사 수정

src/components/common/Feed.jsx, src/components/feed/BookList.jsx, src/components/feed/FollowingFeed.jsx, src/components/profile/MyFeed.jsx, src/pages/FeedPage.jsx, src/pages/MyProfilePage.jsx
피드 컴포넌트 props로 받아오게 수정하였습니다!
Myprofile(내 프로필 페이지에 보이는 피드)
FollowingFeed(홈 피드)
bookList에 가격 쉼표 추가하였씁니다!
!추후에 이미지 사이즈 수정 필요
=> #110 - Feat : 피드 컴포넌트 수정

src/components/common/Feed.jsx, src/components/common/LikeButton.jsx
1. 해당 feed.jsx에 좋아요 기능 추가했습니다.
2. 하트 디자인 피그마에 맞게 일부 수정했습니다.
=> #104 Design: 하트 디자인 일부 수정, 좋아요 기능 추가

src/components/common/Feed.jsx, src/components/feed/UserFollowing.jsx, src/components/followList/Follower.jsx, src/components/followList/Following.jsx, src/components/profile/ProductRegister.jsx
내 프로필에 나오는 상품 css 수정하였습니다.
유저프로필 사진누르면 user/accountname 으로 Link 수정하였습니다.
=> #113 : Fix: 내 프로필 상품 css 수정 & 유저프로필 사진 수정

src/components/common/post/PostViewImg.jsx, src/components/common/post/PostViewImg.style.jsx
PostViewImg.style.jsx 파일 수정 
- 높이값이 없어 이미지가 보여지지 않았던 부분 수정
- 이미지가 1개일 때는 좌우 버튼이 보여지지 않게 수정
=> #116 - Design: PostViewImg.style.jsx CSS 수정

src/components/common/Feed.jsx, src/components/common/LikeButton.jsx, src/components/splash/Splash.jsx
1. splash 화면 문구 수정했습니다.
2.  좋아요 버튼이 모바일 버전에서 살짝? 안맞는거 같아서 수정했습니다.
=> #118 - Design: splash, 좋아요 버튼 css 수정

src/components/common/post/PostViewImg.style.jsx, src/components/common/user/User.jsx, src/components/postView/PostViewContainer.jsx
장문의 댓글 입력 시 레이아웃이 일그러 지는 현상 수정
=> #122 - Design: 댓글 및 이미지 슬라이드 css 수정

src/components/common/Feed.jsx, src/components/common/Product.jsx, src/components/profile/ProductRegister.jsx, src/components/profile/ProfileInfo.jsx, src/components/profile/UserProductRegister.jsx, src/components/profile/UserProfileInfo.jsx, src/pages/UserProfilePage.jsx
유저 프로필페이지에서 유저프로필, 유저 상품, 피드 가져와서 보여주도록 하였습니다!
=> #102 - Feat : 유저프로필 기능

src/components/common/Feed.jsx, src/components/feed/UserFollowing.jsx, src/components/profile/UserProductRegister.jsx, src/components/profile/UserProfileInfo.jsx, src/pages/UserProfilePage.jsx
피드에서 오른쪽에 팔로잉하는 분들 사진 눌러도 그 사람 프로필로 가고
피드에서 눌러도 간닥!!
=> Feat : 피드 내 팔로잉

src/components/common/user/User.jsx, src/components/postView/comment/Comment.jsx, src/components/postView/comment/Comment.style.jsx, src/components/postView/comment/CommetModal.jsx
1. 댓글부분 레이아웃 수정
2. 유저 페이지 연동 수정
=> #126 - Design: 댓글 css 수정

src/components/common/header/FeedHeader.jsx, src/components/common/post/PostViewImg.jsx, src/components/common/user/User.jsx, src/components/navigator/NavigatorMenu.jsx, src/components/postView/comment/Comment.jsx, src/components/profile/ProductRegister.jsx, src/components/profile/UserProductRegister.jsx, src/components/search/SearchCard.jsx, src/pages/FollowerListPage.jsx, src/pages/FollowingListPage.jsx, src/pages/MyProfilePage.jsx, src/pages/SearchPage.jsx, src/pages/UserProfilePage.jsx
=> #128 - Fix: 에러 이미지 처리

src/components/common/Feed.jsx, src/components/profile/UserProductRegister.jsx, src/components/profile/UserProfileInfo.jsx, src/pages/UserProfilePage.jsx
=> #132 - 유저 프로필페이지 수정

src/components/common/feed/Feed.jsx, src/components/common/product/ProductBtn.jsx, src/components/feed/FollowingFeed.jsx, src/components/profile/MyFeed.jsx, src/components/profile/ProductRegister.jsx, src/components/profile/UserProductRegister.jsx, src/pages/UserProfilePage.jsx
common 폴더에서
1. Feed.jsx 
- common/feed/Feed.jsx 로 위치 이동
2. Product.jsx
- 파일 이름 직관적으로 ProductBtn.jsx로 수정
- 파일 위치 common/product/ProductBtn.jsx로 위치 이동
3. 위 파일 이동에 따른 연결된 페이지들 경로 수정
=> #136 - Rename: common 폴더 안에 파일 정리

src/components/splash/SplashButton.style.jsx, src/components/splash/SplashTitle.style.jsx
=> #137 - Design: 스플래쉬 다음 화면 UI

src/components/followList/UserFollow.jsx, src/components/followList/UserFollowBtn.jsx, src/components/profile/UserProfileInfo.jsx
유저프로필에 팔로우, 언팔로우 기능 추가했습니다.
기존에 구현했던 코드 그대로 가져와서 몇 부분 추가만 했습니다~
=> #134 유저프로필 팔로우/언팔로우 기능 추가

src/components/common/feed/Feed.jsx, src/components/postView/PostViewContainer.jsx
포스팅 게시물에서 받아온 값에 image 키값이 있는지 확인하고 그거에 따라 이미지 보여지게 하기
=> #140 - Fix: 포스팅 image 값이 있는지 유무 확인하기

src/components/login/LoginForm.jsx, src/pages/FeedPage.jsx
피드페이지에서 태블릿버전일 때 오른쪽 마이팔로잉 안보이도록 추가하였습니다
=> #156 - Design: 피드페이지 태블릿버전 추가

src/components/common/modal/BottomSheat.style.jsx, src/components/common/product/ProductBtn.jsx, src/components/feed/BookList.jsx
bottomsheat, 피드 북리스트, 마이페이지 북리스트  텍스트 컬러 변경하였습니다!
=> #159 -Design: 다크모드일 때 컬러 변경

src/components/followList/UserFollowBtn.jsx
유저프로필 팔로우 버튼 넓이 수정 
기기 화면마다 알맞게 보이도록 버튼 넓이 수정
=> #161 - Design: 유저프로필 팔로우 버튼 넓이 수정
